[options]
admin_passwd = my_super_secret_password
addons_path = /mnt/odoo-source/addons,/mnt/extra-addons

; --- CẤU HÌNH KẾT NỐI DATABASE TRÊN DOCKER ---
; db_host là tên của service postgres trong file docker-compose (là 'db')
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo_password